	<br><div class="button"><a href="<?= $this->url('Blog', ['action' => 'add']) ?>"><i class="fas fa-plus"></i>Ajouter un poste</a></div><br><br>

<?php foreach ($posts as $post) { ?>
<div class="poste">
    <div class="poste-boddy">
		<div class="poste-header">
        <h2 class="poste-title"><?= $this->escapeHtml($post->titre) ?></h2><div class="date"><?= $this->escapeHtml($post->date) ?></div>
		<div class="poste-tool right">
			<a href="<?= $this->url('Blog', ['action' => 'edit', 'id' => $post->id]) ?>"><i class="fas fa-edit"></i>EDITER</a>
			<a href="<?= $this->url('Blog', ['action' => 'delete', 'id' => $post->id]) ?>"><i class="fas fa-trash-alt"></i>SUPPRIMER</a>
		</div>
		</div>
        <!--<h3 class="poste-title"><?= $this->escapeHtml($post->auteur) ?></h3>-->
		<div class="poste-contenu">
			<img src="img/cat.jpg" width="100%"></img>
		<div class="poste-footer">
			<div class="resume"><?= $this->escapeHtml($post->resume) ?></div><br>	
			<div class="poste-tool left">
				<a href="<?= $this->url('Blog', ['action' => 'details', 'id' => $post->id]) ?>"><i class="far fa-comment"></i>Ajouter un commentaire</a>
			</div>
			<div class="poste-tool right">
				<a href="<?= $this->url('Blog', ['action' => 'details', 'id' => $post->id]) ?>">LIRE LA SUITE...</a>
			</div>
		</div>
		</div>
    </div>     
</div>

<?php } ?>