<!DOCTYPE html>

<body class="accueil">

<div class="navbar">

    <img src="/img/nav.png">
    <img class="logo" src="/img/somabim_w.png">
    <a href="#" class="home"><img src="/img/home_w.png"></a>
</div>

<div class="cellules">

    <div class="line-Cell" id="line-Cell-1">
        <a href="travaux.html" style="text-decoration: none" class="cellule">
            <div class="box"></div>
            <div class="toit"></div>
            <div class="toit2"></div>
            <div class="box2"><p>AMIANTE & PLOMB</p></div>
        </a>

        <a href="travaux.html" style="text-decoration: none" class="cellule">
            <div class="box"></div>
            <div class="toit"></div>
            <div class="toit2"></div>
            <div class="box2"><p>INGENIERIE & METHODES</p></div>
        </a>
    </div>

    <div class="line-Cell" id="line-Cell-2">
        <a href="travaux.html" style="text-decoration: none" class="cellule">
            <div class="box"></div>
            <div class="toit"></div>
            <div class="toit2"></div>
            <div class="box2"><p>CLIENT</p></div>
        </a>

        <a href="<?= $this->url('logements', ['action' => 'OPC']) ?>" style="text-decoration: none" class="cellule">
            <div class="box"></div>
            <div class="toit"></div>
            <div class="toit2"></div>
            <div class="box2"><p>O.P.C</p></div>
        </a>
    </div>

    <div class="line-Cell" id="line-Cell-3">
        <a href="travaux.html" style="text-decoration: none" class="cellule">
            <div class="box"></div>
            <div class="toit"></div>
            <div class="toit2"></div>
            <div class="box2"><p>PARTENAIRES</p></div>
        </a>

        <a href="travaux.html" style="text-decoration: none" class="cellule">
            <div class="box"></div>
            <div class="toit"></div>
            <div class="toit2"></div>
            <div class="box2"><p>TRAVAUX</p></div>
        </a>
    </div>

</div>

</body>
</html>